name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: 

  build:

    runs-on: ubuntu-latest
 
    steps:
    # toma lo que hay en nuestro repositorio 
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # para que valla mas adentro en la busqieda de nuestro historial de commits
        fetch-depth: 0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        

    - name: Debug Version
      run: |
        echo "La nueva versi√≥n es: ${{ steps.version.outputs.version }}"
      # run: echo "new vercion: $NEW_VERSION" 

    - name: Build Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t cezzsa/docker-graphql:$NEW_VERSION .
        docker build -t cezzsa/docker-graphql:latest .
      # toma el cache del primer build para hacer el latest

    - name: Push Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push cezzsa/docker-graphql:$NEW_VERSION
        docker push cezzsa/docker-graphql:latest
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
